using System.Text.RegularExpressions;

namespace StandaloneUiBuilder.Output;

/// <summary>A generated file, relative to the output project folder.</summary>
/// <param name="Regenerate">
/// True if the file is rewritten on every export. False for files that are created once and
/// then belong to the developer, such as code-behind.
/// </param>
/// <param name="Bytes">The file's content when it is not text, such as a picture; Content is then empty.</param>
public sealed record GeneratedFile(string RelativePath, string Content, bool Regenerate, byte[]? Bytes = null)
{
    /// <summary>A picture or other binary file, rewritten on every export.</summary>
    public static GeneratedFile Binary(string relativePath, byte[] bytes) => new(relativePath, "", Regenerate: true, bytes);
}

/// <summary>An export could not be completed. The message is suitable for the user.</summary>
public sealed class ExportException(string message, Exception? innerException = null)
    : Exception(message, innerException);

/// <summary>What an export did to each file.</summary>
public sealed record ExportResult(
    string ProjectFolder,
    IReadOnlyList<string> Created,
    IReadOnlyList<string> Updated,
    IReadOnlyList<string> Kept);

/// <summary>
/// Writes generated files into a project folder. Regenerated files are rewritten only when
/// their content changes; every other existing file is left alone. A regenerated main file
/// that the builder did not create is never overwritten.
/// </summary>
public static partial class ProjectExporter
{
    /// <summary>Text present in every regenerated file, used to recognise the builder's own output.</summary>
    public const string GeneratedMarker = "Generated by Standalone UI Builder";

    [GeneratedRegex(@"^\s*namespace\s+([A-Za-z_][A-Za-z0-9_.]*)", RegexOptions.Multiline)]
    private static partial Regex NamespaceDeclaration();

    /// <param name="folder">The project folder to write into; created if missing.</param>
    /// <param name="guardedFile">A regenerated file that must carry the marker if it already exists.</param>
    /// <param name="namespaceSource">A developer-owned file whose namespace an earlier export chose.</param>
    /// <param name="defaultNamespace">The namespace to use for a first export.</param>
    /// <param name="generate">Produces the files for a given root namespace.</param>
    /// <param name="namespaceSuffix">
    /// What the namespace in <paramref name="namespaceSource"/> adds to the root namespace, if
    /// that file lives in a sub-namespace (".Components.Pages").
    /// </param>
    public static ExportResult Export(
        string folder,
        string guardedFile,
        string namespaceSource,
        string defaultNamespace,
        Func<string, IReadOnlyList<GeneratedFile>> generate,
        string namespaceSuffix = "")
    {
        var created = new List<string>();
        var updated = new List<string>();
        var kept = new List<string>();

        try
        {
            Directory.CreateDirectory(folder);

            var guardedPath = Path.Combine(folder, guardedFile);
            if (File.Exists(guardedPath) && !File.ReadAllText(guardedPath).Contains(GeneratedMarker, StringComparison.Ordinal))
            {
                throw new ExportException(
                    $"\"{guardedPath}\" was not created by Standalone UI Builder, so it was not replaced. "
                    + "Choose another folder, or move that file first.");
            }

            // Keep the namespace of an earlier export, even if the project has been renamed
            // since, so regenerated files still match the developer's code.
            var existing = ExistingNamespace(Path.Combine(folder, namespaceSource));
            if (existing is not null && namespaceSuffix.Length > 0 && existing.EndsWith(namespaceSuffix, StringComparison.Ordinal))
            {
                existing = existing[..^namespaceSuffix.Length];
            }

            var rootNamespace = existing ?? defaultNamespace;

            foreach (var file in generate(rootNamespace))
            {
                var path = Path.Combine(folder, file.RelativePath);
                Directory.CreateDirectory(Path.GetDirectoryName(path)!);
                var exists = File.Exists(path);
                if (exists && (!file.Regenerate || Unchanged(path, file)))
                {
                    kept.Add(file.RelativePath);
                    continue;
                }

                WriteAtomically(path, file);
                (exists ? updated : created).Add(file.RelativePath);
            }
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or NotSupportedException or ArgumentException)
        {
            throw new ExportException($"Could not write the project to \"{folder}\": {ex.Message}", ex);
        }

        return new ExportResult(folder, created, updated, kept);
    }

    private static string? ExistingNamespace(string codeFile)
    {
        if (!File.Exists(codeFile))
        {
            return null;
        }

        var match = NamespaceDeclaration().Match(File.ReadAllText(codeFile));
        return match.Success ? match.Groups[1].Value : null;
    }

    private static bool Unchanged(string path, GeneratedFile file) =>
        file.Bytes is { } bytes ? File.ReadAllBytes(path).AsSpan().SequenceEqual(bytes) : File.ReadAllText(path) == file.Content;

    private static void WriteAtomically(string path, GeneratedFile file)
    {
        var temp = path + ".tmp";
        if (file.Bytes is { } bytes)
        {
            File.WriteAllBytes(temp, bytes);
        }
        else
        {
            File.WriteAllText(temp, file.Content);
        }

        File.Move(temp, path, overwrite: true);
    }
}
