using System.Globalization;
using System.Text;
using StandaloneUiBuilder.Core;

namespace StandaloneUiBuilder.Output;

/// <summary>
/// Writes a screen's view model (see <see cref="DataBindings"/>): a partial class with one
/// property per binding name, each starting from its first control's design value and raising
/// PropertyChanged when it changes, and a partial On…Changed hook per property; and one method
/// per command a Button runs, calling a partial On… method the developer implements. Each target
/// gives the C# type of each kind of value, which follows its controls.
/// </summary>
public static class ViewModelCode
{
    /// <summary>The view model class of a screen: MainViewModel for the first, SettingsViewModel and so on for the others.</summary>
    public static string ClassName(ProjectDocument document, ScreenDocument screen) =>
        CodeNames.ScreenClassName(document, screen, "ViewModel");

    /// <summary>The file a screen's view model is written to.</summary>
    public static string FileName(ProjectDocument document, ScreenDocument screen) => ClassName(document, screen) + ".g.cs";

    /// <param name="type">The C# type for a kind of value.</param>
    /// <param name="initial">The C# expression a property starts with; null for the type's default.</param>
    public static string Generate(
        ProjectDocument document,
        ScreenDocument screen,
        string ns,
        Func<BindingKind, string> type,
        Func<BoundProperty, string?> initial)
    {
        var className = ClassName(document, screen);
        var code = new StringBuilder();
        code.AppendLine("// <auto-generated>");
        code.AppendLine($"// {ProjectExporter.GeneratedMarker} from \"{document.Name.Replace("\r", " ", StringComparison.Ordinal).Replace("\n", " ", StringComparison.Ordinal)}\". This file is replaced on every export.");
        code.AppendLine($"// The values of screen \"{screen.Name}\" that its controls are bound to. To add your own");
        code.AppendLine($"// members, or respond to a change, write another part of the class in {className}.cs:");
        code.AppendLine($"//     public partial class {className} {{ partial void OnNameChanged() => ...; }}");
        code.AppendLine("// </auto-generated>");
        code.AppendLine("#nullable enable");
        code.AppendLine("using System.Collections.Generic;");
        code.AppendLine("using System.ComponentModel;");
        code.AppendLine("using System.Runtime.CompilerServices;");
        code.AppendLine();
        code.AppendLine($"namespace {ns};");
        code.AppendLine();
        code.AppendLine($"public partial class {className} : INotifyPropertyChanged");
        code.AppendLine("{");
        code.AppendLine("    public event PropertyChangedEventHandler? PropertyChanged;");
        foreach (var property in DataBindings.Properties(screen))
        {
            var propertyType = type(property.Kind);
            var field = "_" + char.ToLowerInvariant(property.Name[0]) + property.Name[1..];
            var value = initial(property);
            var bound = string.Join(", ", property.Controls.Select(c => c.Name));
            code.AppendLine();
            code.AppendLine($"    private {propertyType} {field}{(value is null ? "" : " = " + value)};");
            code.AppendLine();
            code.AppendLine($"    /// <summary>Bound to {bound}.</summary>");
            code.AppendLine($"    public {propertyType} {property.Name}");
            code.AppendLine("    {");
            code.AppendLine($"        get => {field};");
            code.AppendLine("        set");
            code.AppendLine("        {");
            code.AppendLine($"            if (SetProperty(ref {field}, value))");
            code.AppendLine("            {");
            code.AppendLine($"                On{property.Name}Changed();");
            code.AppendLine("            }");
            code.AppendLine("        }");
            code.AppendLine("    }");
            code.AppendLine();
            code.AppendLine($"    partial void On{property.Name}Changed();");
        }

        foreach (var command in DataBindings.Commands(screen))
        {
            var buttons = string.Join(", ", command.Buttons.Select(c => c.Name));
            code.AppendLine();
            code.AppendLine($"    /// <summary>Run by {buttons} when clicked; implement On{command.Name} in your part of the class.</summary>");
            code.AppendLine($"    public void {command.Name}() => On{command.Name}();");
            code.AppendLine();
            code.AppendLine($"    partial void On{command.Name}();");
        }

        code.AppendLine();
        code.AppendLine("    /// <summary>Raises PropertyChanged for a property.</summary>");
        code.AppendLine("    public void OnPropertyChanged([CallerMemberName] string? propertyName = null) =>");
        code.AppendLine("        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));");
        code.AppendLine();
        code.AppendLine("    private bool SetProperty<T>(ref T field, T value, [CallerMemberName] string? propertyName = null)");
        code.AppendLine("    {");
        code.AppendLine("        if (EqualityComparer<T>.Default.Equals(field, value))");
        code.AppendLine("        {");
        code.AppendLine("            return false;");
        code.AppendLine("        }");
        code.AppendLine();
        code.AppendLine("        field = value;");
        code.AppendLine("        OnPropertyChanged(propertyName);");
        code.AppendLine("        return true;");
        code.AppendLine("    }");
        code.AppendLine("}");
        return code.ToString();
    }

    /// <summary>The statement a button's click handler uses to run its command, if it has one.</summary>
    public static string? CommandStatement(ControlDocument button) =>
        button.Properties.Command is { } command ? $"ViewModel.{command}();" : null;

    /// <summary>The design's text of the property's first control, as a C# string literal.</summary>
    public static string TextLiteral(BoundProperty property) => Literal(property.First.Properties.Text ?? "");

    /// <summary>The design's checked state of the property's first control.</summary>
    public static string FlagLiteral(BoundProperty property) => property.First.Properties.IsChecked == true ? "true" : "false";

    /// <summary>The design's value of the property's first control.</summary>
    public static string NumberLiteral(BoundProperty property) =>
        (property.First.Properties.Value ?? property.First.Properties.Minimum ?? 0).ToString(CultureInfo.InvariantCulture);

    public static string Literal(string value)
    {
        var text = new StringBuilder("\"");
        foreach (var c in value)
        {
            text.Append(c switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\r' => "\\r",
                '\n' => "\\n",
                '\t' => "\\t",
                < ' ' => $"\\u{(int)c:X4}",
                _ => c.ToString(),
            });
        }

        return text.Append('"').ToString();
    }
}
