using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using StandaloneUiBuilder.Core;

namespace StandaloneUiBuilder.Output.Wpf;

/// <summary>A generated source file, relative to the output project folder.</summary>
/// <param name="Regenerate">
/// True if the file is rewritten on every export. False for files that are created once and
/// then belong to the developer, such as code-behind.
/// </param>
public sealed record GeneratedFile(string RelativePath, string Content, bool Regenerate);

/// <summary>
/// Generates a complete WPF application from a builder project: a project file, App and a
/// MainWindow whose Canvas holds the screen's controls at their designed positions.
/// Output is deterministic: the same document always produces the same text.
/// </summary>
public static partial class WpfGenerator
{
    public const string WindowClassName = "MainWindow";

    /// <summary>Text present in every regenerated file, used to recognise our own output.</summary>
    public const string GeneratedMarker = "Generated by Standalone UI Builder";

    // Keep these in step with the designer's ControlFactory so the generated window looks the
    // same as the design surface. A Windows test compares the two.
    private const string LabelPadding = "2,0";

    private static readonly HashSet<string> CSharpKeywords =
    [
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class",
        "const", "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event",
        "explicit", "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto", "if",
        "implicit", "in", "int", "interface", "internal", "is", "lock", "long", "namespace", "new", "null",
        "object", "operator", "out", "override", "params", "private", "protected", "public", "readonly",
        "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string", "struct",
        "switch", "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe",
        "ushort", "using", "virtual", "void", "volatile", "while",
    ];

    // Names that would clash with members the generated window already has.
    private static readonly HashSet<string> ReservedNames = new(StringComparer.Ordinal)
    {
        WindowClassName, "InitializeComponent", "Content", "Title", "Width", "Height", "Name",
        "Resources", "Parent", "Owner", "Icon", "Left", "Top", "Background", "Foreground",
    };

    [GeneratedRegex(@"[^A-Za-z0-9]+")]
    private static partial Regex NonAlphanumeric();

    /// <summary>
    /// Returns reasons the document cannot be exported to WPF as it stands, or an empty list.
    /// </summary>
    public static IReadOnlyList<string> Check(ProjectDocument document)
    {
        var problems = new List<string>();
        foreach (var control in document.Screen.Controls)
        {
            if (CSharpKeywords.Contains(control.Name))
            {
                problems.Add($"\"{control.Name}\" is a C# keyword and cannot be used as a control name in WPF code. Rename it.");
            }
            else if (ReservedNames.Contains(control.Name))
            {
                problems.Add($"\"{control.Name}\" clashes with a member of the generated window. Rename the control.");
            }
        }

        return problems;
    }

    /// <summary>
    /// Turns a project name into a C# namespace: "Customer form" becomes "CustomerForm".
    /// </summary>
    public static string ToNamespace(string projectName)
    {
        var words = NonAlphanumeric().Split(projectName).Where(w => w.Length > 0);
        var name = string.Concat(words.Select(w => char.ToUpperInvariant(w[0]) + w[1..]));
        if (name.Length == 0)
        {
            return "GeneratedApp";
        }

        return char.IsDigit(name[0]) ? "App" + name : name;
    }

    public static IReadOnlyList<GeneratedFile> Generate(ProjectDocument document, string rootNamespace) =>
    [
        new($"{rootNamespace}.csproj", ProjectFileText(rootNamespace), Regenerate: false),
        new("App.xaml", AppXaml(rootNamespace), Regenerate: false),
        new("App.xaml.cs", AppCode(rootNamespace), Regenerate: false),
        new($"{WindowClassName}.xaml", WindowXaml(document, rootNamespace), Regenerate: true),
        new($"{WindowClassName}.xaml.cs", WindowCode(rootNamespace), Regenerate: false),
    ];

    public static string WindowXaml(ProjectDocument document, string rootNamespace)
    {
        var screen = document.Screen;
        var xaml = new StringBuilder();
        xaml.AppendLine($"<!-- {GeneratedMarker} from \"{Comment(document.Name)}\". This file is replaced on every export;");
        xaml.AppendLine($"     put your own code in {WindowClassName}.xaml.cs. -->");
        xaml.AppendLine($"<Window x:Class=\"{rootNamespace}.{WindowClassName}\"");
        xaml.AppendLine("        xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\"");
        xaml.AppendLine("        xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\"");
        xaml.AppendLine($"        Title=\"{Attribute(document.Name)}\"");
        xaml.AppendLine("        SizeToContent=\"WidthAndHeight\"");
        xaml.AppendLine("        ResizeMode=\"CanMinimize\"");
        xaml.AppendLine("        UseLayoutRounding=\"True\">");
        xaml.AppendLine($"    <Canvas Width=\"{Number(screen.Width)}\" Height=\"{Number(screen.Height)}\">");

        foreach (var control in screen.Controls)
        {
            AppendControl(xaml, control);
        }

        xaml.AppendLine("    </Canvas>");
        xaml.AppendLine("</Window>");
        return xaml.ToString();
    }

    private static void AppendControl(StringBuilder xaml, ControlDocument control)
    {
        var properties = control.Properties;
        var element = control.Type.ToString();
        var attributes = new List<string>
        {
            $"x:Name=\"{control.Name}\"",
            $"Canvas.Left=\"{Number(control.X)}\"",
            $"Canvas.Top=\"{Number(control.Y)}\"",
            $"Width=\"{Number(control.Width)}\"",
            $"Height=\"{Number(control.Height)}\"",
        };

        switch (control.Type)
        {
            case ControlType.Label:
                attributes.Add($"Padding=\"{LabelPadding}\"");
                attributes.Add("VerticalContentAlignment=\"Center\"");
                attributes.Add($"Content=\"{Attribute(LiteralAccessText(properties.Text))}\"");
                break;
            case ControlType.Button:
                attributes.Add($"Content=\"{Attribute(LiteralAccessText(properties.Text))}\"");
                break;
            case ControlType.TextBox:
                attributes.Add("VerticalContentAlignment=\"Center\"");
                attributes.Add($"Text=\"{Attribute(properties.Text ?? "")}\"");
                break;
            case ControlType.CheckBox:
                attributes.Add("VerticalContentAlignment=\"Center\"");
                attributes.Add($"IsChecked=\"{(properties.IsChecked == true ? "True" : "False")}\"");
                attributes.Add($"Content=\"{Attribute(LiteralAccessText(properties.Text))}\"");
                break;
            case ControlType.ComboBox:
                attributes.Add("VerticalContentAlignment=\"Center\"");
                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(control), control.Type, "Unknown control type.");
        }

        var items = control.Type == ControlType.ComboBox ? properties.Items ?? [] : [];
        var opening = $"        <{element} {string.Join(" ", attributes)}";
        if (items.Count == 0)
        {
            xaml.AppendLine(opening + " />");
            return;
        }

        xaml.AppendLine(opening + ">");
        foreach (var item in items)
        {
            xaml.AppendLine($"            <ComboBoxItem Content=\"{Attribute(item)}\" />");
        }

        xaml.AppendLine($"        </{element}>");
    }

    private static string WindowCode(string rootNamespace) => $$"""
        using System.Windows;

        namespace {{rootNamespace}};

        // Created once by Standalone UI Builder and never overwritten: add your code here.
        // The controls are declared in {{WindowClassName}}.xaml, which is regenerated on every export.
        public partial class {{WindowClassName}} : Window
        {
            public {{WindowClassName}}()
            {
                InitializeComponent();
            }
        }

        """;

    private static string AppXaml(string rootNamespace) => $$"""
        <Application x:Class="{{rootNamespace}}.App"
                     xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                     StartupUri="{{WindowClassName}}.xaml">
        </Application>

        """;

    private static string AppCode(string rootNamespace) => $$"""
        using System.Windows;

        namespace {{rootNamespace}};

        public partial class App : Application
        {
        }

        """;

    private static string ProjectFileText(string rootNamespace) => $$"""
        <Project Sdk="Microsoft.NET.Sdk">

          <PropertyGroup>
            <OutputType>WinExe</OutputType>
            <TargetFramework>net10.0-windows</TargetFramework>
            <Nullable>enable</Nullable>
            <ImplicitUsings>enable</ImplicitUsings>
            <UseWPF>true</UseWPF>
            <RootNamespace>{{rootNamespace}}</RootNamespace>
          </PropertyGroup>

        </Project>

        """;

    /// <summary>
    /// Label, Button and CheckBox treat "_" as an access-key marker. The designer shows text
    /// literally, so each underscore is doubled to display as itself.
    /// </summary>
    private static string LiteralAccessText(string? text) => (text ?? "").Replace("_", "__", StringComparison.Ordinal);

    private static string Number(int value) => value.ToString(CultureInfo.InvariantCulture);

    private static string Attribute(string value)
    {
        var escaped = new StringBuilder(value.Length);
        foreach (var c in value)
        {
            escaped.Append(c switch
            {
                '&' => "&amp;",
                '<' => "&lt;",
                '>' => "&gt;",
                '"' => "&quot;",
                '\n' => "&#10;",
                '\r' => "&#13;",
                '\t' => "&#9;",

                // A leading "{" would be read as a markup extension.
                '{' when escaped.Length == 0 => "{}{",
                _ => c.ToString(),
            });
        }

        return escaped.ToString();
    }

    // "--" is not allowed inside an XML comment.
    private static string Comment(string value) => value.Replace("--", "- -", StringComparison.Ordinal);
}
